### ISSUE TITLE
Provide Java based tutorials for pub/sub, persistence, & request/reply

### ISSUE THREAD

**Issue by mdspielman** [SolaceSamples/solace-samples-rest-messaging#2]
Based on user feedback, it would be nice to have java tutorials to demonstrate the simple tutorials like pub/sub, persistence, and request / reply.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
