### ISSUE TITLE
Solace Cloud instructions for Configuring a REST Delivery Point

### ISSUE THREAD

**Issue by solace-se** [SolaceSamples/solace-samples-rest-messaging#23]
Hi Docs team.  I have a customer who would like to configure this graphically using the Solace Cloud Gui.  Can we add these instructions rather than forcing to use the CLI?

Cheers Phil.

**Comment by aaron-613** [comment]
Hello @solace-se , not sure who you are.  Cleaning/closing old Issues.

Please note that the tutorials have been updated to include screenshots for configuring an RDP in PS+Manager.  https://tutorials.solace.dev/rest-messaging/publish-subscribe/

Also, these might be of interest:
https://www.youtube.com/watch?v=INMrSL2fA3E
https://youtu.be/TeKgwMz1pZY
